name: update github hosts
on:
  # push:
  #   branches: [ "main" ]
  schedule:
    - cron: "* 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Set_BuildTime:
    runs-on: ubuntu-22.04
    outputs:
      BUILD_TIME: ${{ steps.set_buildtime.outputs.BUILD_TIME }}
    steps:
      - name: Set build time
        id: set_buildtime
        run: echo "BUILD_TIME=$(date +'%s')" >> $GITHUB_OUTPUT
    
      - name: update hosts
        id: get_latest
        run: |
          sudo curl -s https://hosts.gitcdn.top/hosts.txt |sed -e '/^s*$/d' -e '/^#.*/d' -e 's/^/add address=/g' -e 's/    */  name=/g' |sed -e $'1i\\\n/ip dns static' |sed '$a \/' |sed '$a /file remove hosts.rsc'>hosts.rsc

      - name: Create Release tag hosts.rsc
        uses: softprops/action-gh-release@v2
        with:
          name: "BUILD_TIME=$(date +'%s')"
          files: |
            hosts.rsc
